### ISSUE TITLE
Che senso ha?

### ISSUE THREAD

**Issue by DoubleHub** [aleven/jpec-server#2]
Che senso ha mettere questo intero monolite su GitHub se poi non metti a disposizione la classe più importante ossia it.attocchi.mail.utils.MailSender?

**Comment by mattocchi** [comment]
Come indicato nel README il progetto dipende da una libreria esterna (comune fra vari progetti) https://github.com/aleven/webapp-common (open source anch'essa). purtroppo non era ancora pubblicato su Maven-Central ed ho linkato nel readme. Ora è pubblicata, verifico ed aggiorno le dipendenze maven.

**Comment by DoubleHub** [comment]
Ora che gli artefatti sono su maven ha tutto più senso. Grazie per la tempestiva risposta.
